---
capacity: 200
plan: free
local_db: sqlite3:C:/IronFoundry/mssql/db/mssql_node.db
base_dir: C:/IronFoundry/mssql
# sqlcmd_bin: 'C:/Program Files/Microsoft SQL Server/100/Tools/Binn/sqlcmd.exe' # Note: optional
mbus: nats://nats:nats@192.168.171.129:4222
index: 0
logging:
  level: error
  file: C:/IronFoundry/mssql/log/mssql_node.log
pid: C:/IronFoundry/mssql/run/mssql_node.pid
node_id: mssql_node_1

supported_versions: ["10.50.2500"]
default_version: "10.50.2500"

max_db_size:     256 # Note: in MB
initial_db_size:   4 # Note: in MB

max_long_query: 3
max_long_tx: 30 # Note: in seconds
max_user_conns: 20

migration_nfs: C:/var/mnt/appcloud
mssql:
  host: 127.0.0.1
  port: 1433
  user: sa
  pass: Password123
connection_pool_size: 5
connection_wait_timeout: 10

# ip_route: 127.0.0.1 # NB: optional, only set if necessary
# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
# op_time_limit: 6
